services:
  - type: web
    name: firstpass-poc
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate --noinput && python manage.py seed_demo && gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: PYTHON_VERSION
        value: "3.12.10"
