# Generated by Django 6.1 on 2026-08-30 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('headline', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=120)),
                ('skills', models.JSONField(default=list)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('education', models.CharField(max_length=200)),
                ('preferred_role', models.CharField(max_length=120)),
                ('preferred_salary_min', models.PositiveIntegerField()),
                ('preferred_work_arrangement', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], max_length=20)),
                ('summary', models.TextField()),
                ('portfolio_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=160)),
                ('title', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=160)),
                ('role_summary', models.TextField()),
                ('salary_min', models.PositiveIntegerField()),
                ('salary_max', models.PositiveIntegerField()),
                ('work_arrangement', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], max_length=20)),
                ('reason_for_interest', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('saved', 'Saved for Later'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.candidate')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.employer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
